### ISSUE TITLE
Create Logger utility

### ISSUE THREAD

**Issue by francesco-romano** [robotology-playground/codyco-commons#1]
We should add some macros / classes to handle logging throughout codyco projects.

To be "caught" by yarp logging facility we should support (at least) the following formats:

```
[DEBUG] stuff
[ERROR] stuff
[INFO] stuff
```

The easiest way is a macro like the one already present in this library.

Opinions on this?
@traversaro @naveenoid @jeljaik ?

(btw: @traversaro We already discussed a bit of this, but I can't find the original issue. Do you remember where it is?)

**Comment by andreadelprete** [comment]
A nice feature I've always found useful for logging is having messages that are printed at frequencies lower than the thread's. This is not trivial to achieve, especially for error messages, because in that case you wanna be sure that the message gets printed the first time the error occurs, but it is not printed if the error persists in the successive loops. If I haven't been clear just tell me and I'll give you an example.
Anyway I started doing something in this direction [here](https://github.com/robotology/codyco-modules/blob/master/src/modules/wholeBodyReach/include/wholeBodyReach/Logger.h).

**Comment by randaz81** [comment]
General considerations (in random order)
- Just for clarification for Andre (I don't know if he is aware of it),
  there exist an logger system (library) in yarprun_log branch of yarp that
  will become official in the next weeks. If you want to try it, you also
  need to download the get the GUI from qtyarp repository.
- For now just put [ERROR], [WARNING], [INFO], [DEBUG] in the prints of
  your modules. The logger will capture everything, but marked messages will
  be searchable and coloured in the GUI log.
- Of course there will be macros. Currently a logger.h in icubmod provides
  functions like yDebug(), yError() etc. Since these schortcuts are visible
  only inside the icub scope, we need to discuss with Lorenzo and Paul a fine
  location in yarp to make them available generally.
- I understand perfectly. We'll try to add the feature to the yarp logger.
  Please tell us if there are additional ideas. We also discussed a trace
  functionality for the threads, but this is currently not possibile: in the
  log you currently get the id of the process, not the id of the thread.
  Maybe in the future.

2014-08-26 11:12 GMT+02:00 Andrea Del Prete notifications@github.com:
